/* eslint-disable import/prefer-default-export */
export const AT = {
  FETCH_USERS_PENDING: 'FETCH_USERS_PENDING',
  FETCH_USERS_SUCCESS: 'FETCH_USERS_SUCCESS',
  FETCH_USERS_ERROR: 'FETCH_USERS_ERROR',
  GET_USER_DETAILS: 'GET_USER_DETAILS'
};
